@host = http://localhost:9000/api


POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "id":"123456789",
    "email":"luongminhthanh91@gmail.com",
    "password":"123456",
    "name":"minh thanh",
    "phone":"0704543052"
}
###

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"luongminhthanh91@gmail.com",
    "password":"123456"
}
###
GET http://localhost:9000/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGZmMGM1OS1iYmIxLTRlZjUtODJhNy02YWYyN2QwYTM2OTMiLCJpYXQiOjE2Njk2NTAyMjgsImV4cCI6MTY2OTY1MDI1OH0.SJVFMK5Z3tY_yeT6SNU00dVkDDRnCTzH45ZjB_klgfk


###

GET  {{host}}/auth/getlist HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGZmMGM1OS1iYmIxLTRlZjUtODJhNy02YWYyN2QwYTM2OTMiLCJpYXQiOjE2Njk1NTM0ODEsImV4cCI6MTY2OTU1MzU0MX0._bOSwkAKHZk_VXO5P54YwJLTW1g47aGfVYgIfb4um7k
###
POST {{host}}/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGZmMGM1OS1iYmIxLTRlZjUtODJhNy02YWYyN2QwYTM2OTMiLCJpYXQiOjE2Njk1NTM0NTYsImV4cCI6MTY2OTU2MDY1Nn0.9cXNI-jYalJsHYpaY2Q05QTAnAJxLhrtoJjcOmst5V0"
}

###

DELETE {{host}}/auth/logout HTTP/1.1
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1OGZmMGM1OS1iYmIxLTRlZjUtODJhNy02YWYyN2QwYTM2OTMiLCJpYXQiOjE2Njk1NjQ3MTEsImV4cCI6MTY2OTU3MTkxMX0.XqvrhBOZ1vCPCw1w-IOgorsclcmQ4tXDyWmiVcXt1_E"

}

###

get {{host}}/admin/deleteCategory/4 HTTP/1.1
Content-Type: application/json

###
post {{host}}/brand/storeBrand HTTP/1.1
Content-Type: application/json

{
    "brand_name": "Đồng Tháp"
}

###

get {{host}}/ subcate/subcategoryHTTP/1.1
Content-Type: application/json

###
get {{host}}/cate/category HTTP/1.1
Content-Type: application/json
###
get {{host}}/auth/getAllUser HTTP/1.1
Content-Type: application/json

###
get {{host}}/product/getSubCate/ddde7b0c-0b3f-411a-9978-7fc7cb7ec6ad HTTP/1.1
Content-Type: application/json
###
get {{host}}/product/storeProduct HTTP/1.1
Content-Type: application/json

{
    "categories_id":"ddde7b0c-0b3f-411a-9978-7fc7cb7ec6ad"
}
###
get {{host}}/product/product HTTP/1.1
Content-Type: application/json

###
get {{host}}/coup/storeNewslater HTTP/1.1
Content-Type: application/json

{
    "categories_id":"ddde7b0c-0b3f-411a-9978-7fc7cb7ec6ad"
}
###

POST {{host}}/cart/addToCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NWQ0YzlhNS05NjdiLTQzNDMtOGJjZS1mODY3NDZiNzhjNDQiLCJpYXQiOjE2NjkyMjE2MDAsImV4cCI6MTY2OTIyNTIwMH0.p0MCKbyBraSFmPAbhpz-Bq97yafdcfqL8YmfZ3jH5BQ

{
    "productId":"06fa3ae7-badc-408f-9a2c-f5d2243f7d70"
}
###
GET {{host}}/cart/getCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NWQ0YzlhNS05NjdiLTQzNDMtOGJjZS1mODY3NDZiNzhjNDQiLCJpYXQiOjE2NjkyMjE2MDAsImV4cCI6MTY2OTIyNTIwMH0.p0MCKbyBraSFmPAbhpz-Bq97yafdcfqL8YmfZ3jH5BQ

###
DELETE  {{host}}/cart/removeCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NWQ0YzlhNS05NjdiLTQzNDMtOGJjZS1mODY3NDZiNzhjNDQiLCJpYXQiOjE2NjkyMjE2MDAsImV4cCI6MTY2OTIyNTIwMH0.p0MCKbyBraSFmPAbhpz-Bq97yafdcfqL8YmfZ3jH5BQ

{
    "productId":"06fa3ae7-badc-408f-9a2c-f5d2243f7d70"
}

###
DELETE  {{host}}/cart/deleteCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NWQ0YzlhNS05NjdiLTQzNDMtOGJjZS1mODY3NDZiNzhjNDQiLCJpYXQiOjE2NjkyMjE2MDAsImV4cCI6MTY2OTIyNTIwMH0.p0MCKbyBraSFmPAbhpz-Bq97yafdcfqL8YmfZ3jH5BQ

###
POST {{host}}/wishlist/addToWishList/2f51854e-9d9d-4250-9ba7-db678d3fac8d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NWQ0YzlhNS05NjdiLTQzNDMtOGJjZS1mODY3NDZiNzhjNDQiLCJpYXQiOjE2Njk4MjExNTQsImV4cCI6MTY2OTgyNDc1NH0.INzI6oUK6wlsTvUM7ipwRVVTyrU4oYiiB8pJCegepMQ



